### ISSUE TITLE
fail to allocate future buffer for task

### ISSUE THREAD

**Issue by DavidPeleg6** [flexflow/FlexFlow#200] opened 2021-05-25 14:38 UTC
I am trying to run the following script from the test.sh file:
./flexflow_python $FF_HOME/examples/python/native/alexnet.py -ll:py 1 -ll:gpu 4 -ll:fsize 8000 -ll:cpu 28 -ll:zsize 12192 --epochs 40

and get the following error:
[0 - 7fd3f4340700]   16.466406 {5}{runtime}: [error 576] LEGION ERROR: Failed to allocate eager future buffer for task flexflow_top_level_task (UID 1) because Visible to all processors on a node memory 1e00000000000000 is full. This is an eager allocation so you must adjust the percentage of this mememory dedicated for eager allocations with '-lg:eager_alloc_percentage' flag on the command line. (from file /usr/FlexFlow/deps/legion/runtime/legion/runtime.cc:9971)
For more information see:
http://legion.stanford.edu/messages/error_code.html#error_code_576

I tried playing with the -lg flag

**Comment by jiazhihao** [comment] 2021-05-25 18:22
This is due to a recent change in Legion. We can changed the default eager allocation percentage to avoid this error. Let us know if you still encounter this error after pulling the changes in the master branch. Note that the commit `867f27014` also updates the Legion submodule, so you will need to do a `git submodule update`

**Comment by DavidPeleg6** [comment] 2021-05-26 09:24
I am currently in the master branch (commit f0913c24cd056a09797a3261d9f4c750cd062208).
I pulled and rebuild the repository and I still get the same error.
However, after adding the flag -lg:eager_alloc_percentage 60 ,
flexflow was able to run a couple of iterations before exhibiting this error.
note that I also get a warning in one of the steps:
[0 - 7f2be0d74700]    4.991553 {4}{runtime}: [warning 1097] LEGION WARNING: WARNING: The runtime has failed to memoize the trace more than 5 times, due to the absence of a replayable template. It is highly likely that trace 201 will not be memoized for the rest of execution. The most recent template was not replayable for the following reason: precondition not subsumed by postcondition. Please change the mapper to stop making memoization requests. (from file /usr/FlexFlow/deps/legion/runtime/legion/legion_trace.cc:2025)
For more information see:
http://legion.stanford.edu/messages/warning_code.html#warning_code_1097

**Comment by jiazhihao** [comment] 2021-05-26 22:09
@DavidPeleg6 This is a warning from Legion and should be deterministically reproducible. Can you share with us the command line to produce this error? We will look into it.

**Comment by DavidPeleg6** [comment] 2021-05-30 11:48
I first ran the optimizer on a test and the warning (and error) pop up when I run the test again with the exported strategy file:
step 1:
./flexflow_python $FF_HOME/examples/python/keras/seq_mnist_mlp.py -ll:py 1 -ll:gpu 4 -ll:fsize 8192 -ll:zsize 12192 --export strategy.txt --budget 1000
step 2:
./flexflow_python $FF_HOME/examples/python/keras/seq_mnist_mlp.py -ll:py 1 -ll:gpu 4 -ll:fsize 8192 -ll:zsize 12192 --import strategy.txt

the warning and error:
[0 - 7fd6b6f0c700]    7.733516 {4}{runtime}: [warning 1097] LEGION WARNING: WARNING: The runtime has failed to memoize the trace more than 5 times, due to the absence of a replayable template. It is highly likely that trace 101 will not be memoized for the rest of execution. The most recent template was not replayable for the following reason: precondition not subsumed by postcondition. Please change the mapper to stop making memoization requests. (from file /usr/FlexFlow/deps/legion/runtime/legion/legion_trace.cc:2025)
For more information see:
http://legion.stanford.edu/messages/warning_code.html#warning_code_1097

[0 - 7fd65c6f3700]    8.418881 {5}{runtime}: [error 576] LEGION ERROR: Failed to allocate eager future buffer for task flexflow_top_level_task (UID 1) because Visible to all processors on a node memory 1e00000000000000 is full. This is an eager allocation so you must adjust the percentage of this mememory dedicated for eager allocations with '-lg:eager_alloc_percentage' flag on the command line. (from file /usr/FlexFlow/deps/legion/runtime/legion/runtime.cc:9971)
For more information see:
http://legion.stanford.edu/messages/error_code.html#error_code_576

**Comment by DavidPeleg6** [comment] 2021-06-27 15:38
@jiazhihao Is there any additional information that I can provide to help you understand the source of the problem?

**Comment by eddy16112** [comment] 2021-06-28 07:37
This should be fixed once you update the Legion to the latest flexflow branch.

**Comment by shengchengwang** [comment] 2021-09-02 06:21
I am also in the master branch recently (pulled and build the repo just now), and still, get the same error:
step1:
./dlrm -ll:gpu 8 -ll:fsize 12000 -ll:zsize 20000 --arch-sparse-feature-size 64 --arch-embedding-size 1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000 --arch-mlp-bot 64-512-512-64 --arch-mlp-top 576-1024-1024-1024-1 --batch-size 1024 --budget 1000 --export dlrm_strategy.txt
step2:
./dlrm -ll:gpu 8 -ll:fsize 12000 -ll:zsize 20000 --arch-sparse-feature-size 64 --arch-embedding-size 1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000 --arch-mlp-bot 64-512-512-64 --arch-mlp-top 576-1024-1024-1024-1 --batch-size 1024 --import dlrm_strategy.txt

And I got the same error:
[0 - 7f4f380aa000]   10.467377 {5}{runtime}: [error 576] LEGION ERROR: Failed to allocate eager future buffer for task top_level (UID 1) because Visible to all processors on a node memory 1e00000000000000 is full. This is an eager allocation so you must adjust the percentage of this mememory dedicated for eager allocations with '-lg:eager_alloc_percentage' flag on the command line. (from file /root/projects/FlexFlow/deps/legion/runtime/legion/runtime.cc:10420)
For more information see:
http://legion.stanford.edu/messages/error_code.html#error_code_576

Plz, help me to fix the issue. Thx

**Comment by shengchengwang** [comment] 2021-09-02 08:03
> This should be fixed once you update the Legion to the latest flexflow branch.
I am also in the master branch recently (pulled and build the repo just now), and still, get the same error:
step1:
./dlrm -ll:gpu 8 -ll:fsize 12000 -ll:zsize 20000 --arch-sparse-feature-size 64 --arch-embedding-size 1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000 --arch-mlp-bot 64-512-512-64 --arch-mlp-top 576-1024-1024-1024-1 --batch-size 1024 --budget 1000 --export dlrm_strategy.txt
step2:
./dlrm -ll:gpu 8 -ll:fsize 12000 -ll:zsize 20000 --arch-sparse-feature-size 64 --arch-embedding-size 1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000 --arch-mlp-bot 64-512-512-64 --arch-mlp-top 576-1024-1024-1024-1 --batch-size 1024 --import dlrm_strategy.txt

And I got the same error:
[0 - 7f4f380aa000] 10.467377 {5}{runtime}: [error 576] LEGION ERROR: Failed to allocate eager future buffer for task top_level (UID 1) because Visible to all processors on a node memory 1e00000000000000 is full. This is an eager allocation so you must adjust the percentage of this mememory dedicated for eager allocations with '-lg:eager_alloc_percentage' flag on the command line. (from file /root/projects/FlexFlow/deps/legion/runtime/legion/runtime.cc:10420)
For more information see:
http://legion.stanford.edu/messages/error_code.html#error_code_576

Plz, help me to fix the issue. Thx

**Comment by shengchengwang** [comment] 2021-09-03 02:39
> I am trying to run the following script from the test.sh file:
> ./flexflow_python $FF_HOME/examples/python/native/alexnet.py -ll:py 1 -ll:gpu 4 -ll:fsize 8000 -ll:cpu 28 -ll:zsize 12192 --epochs 40
> 
> and get the following error:
> [0 - 7fd3f4340700] 16.466406 {5}{runtime}: [error 576] LEGION ERROR: Failed to allocate eager future buffer for task flexflow_top_level_task (UID 1) because Visible to all processors on a node memory 1e00000000000000 is full. This is an eager allocation so you must adjust the percentage of this mememory dedicated for eager allocations with '-lg:eager_alloc_percentage' flag on the command line. (from file /usr/FlexFlow/deps/legion/runtime/legion/runtime.cc:9971)
> For more information see:
> http://legion.stanford.edu/messages/error_code.html#error_code_576
> 
> I tried playing with the -lg flag

Hi David, did you fix this issue?

**Comment by eddy16112** [comment] 2021-09-03 03:07
you can try to add "-lg:eager_alloc_percentage 40" to your cmd line. if 40 is not enough, try to increase the number like 50 60 ...

**Comment by shengchengwang** [comment] 2021-09-03 03:21
> @shengchengwang you can try to add "-lg:eager_alloc_percentage 40" to your cmd line. if 40 is not enough, try to increase the number like 50 60 ...

Thx a lot. Will give it a try.

**Comment by jiazhihao** [comment] 2021-09-03 03:21
@shengchengwang I just realized that you are playing with the DLRM example. You can reduce `MAX_NUM_SAMPLES` to be your per-GPU batch size, which is 1024 in your script, by editing this line: https://github.com/flexflow/FlexFlow/blob/master/examples/cpp/DLRM/dlrm.h#L17.

This should help you resolve the issue. Once the issue disappears, you no longer need to set `-lg:eager_alloc_percentage` explicitly.

**Comment by shengchengwang** [comment] 2021-09-03 03:47
> @shengchengwang I just realized that you are playing with the DLRM example. You can reduce `MAX_NUM_SAMPLES` to be your per-GPU batch size, which is 1024 in your script, by editing this line: https://github.com/flexflow/FlexFlow/blob/master/examples/cpp/DLRM/dlrm.h#L17.
> 
> This should help you resolve the issue. Once the issue disappears, you no longer need to set `-lg:eager_alloc_percentage` explicitly.

Thx Zhihao !

**Closed** 2022-11-03 06:32 UTC
