### ISSUE TITLE
test.sh failures

### ISSUE THREAD

**Issue by DavidPeleg6** [flexflow/FlexFlow#205] opened 2021-05-30 15:22 UTC
I ran the test.sh file and stumbled on to multiple errors that I tried to handled according to previously submitted issues.
After editing the test.sh file according to your answers  in https://github.com/flexflow/FlexFlow/issues/190 and https://github.com/flexflow/FlexFlow/issues/196 more of the tests pass but I still get errors as mentioned in the following tickets: 

https://github.com/flexflow/FlexFlow/issues/166 and https://github.com/flexflow/FlexFlow/issues/200 .

Attached is my updated version of test.sh (with increase fsize values).
[test.sh](https://github.com/flexflow/FlexFlow/files/6574248/test.sh.txt)
- Under what hardware configuration were the tests of the master branch verified?

**Comment by DavidPeleg6** [comment] 2021-06-06 15:03
@jiazhihao most of my questions recently relate to this ticket.  Though I want to be able to run all of test.sh successfully (can you verify that that is possible on the master branch?) the largest issue I have is with the test (#abc ):

`./flexflow_python $FF_HOME/examples/python/pytorch/mnist_mlp.py -ll:py 1 -ll:gpu 2 -ll:fsize 8192 -ll:zsize 12192 -ll:cpu 28 --export strategy.txt --budget 1000 --enable-parameter-parallel --enable-attribute-parallel`

` ./flexflow_python $FF_HOME/examples/python/pytorch/mnist_mlp.py -ll:py 1 -ll:gpu 2 -ll:fsize 8192 -ll:zsize 12192 -ll:cpu 28 --import strategy.txt`
-which generates this log  trace:  [results.txt](https://github.com/flexflow/FlexFlow/files/6604373/results.txt)
The strategy that Iused was: [strategy.txt](https://github.com/flexflow/FlexFlow/files/6604375/strategy.txt)

Even when I lower the amount of gpu's used which allows the test to run. the legion warning 1097 appears every 5 iterations and the runtime is extremely long (exact time). In contrast, when I don't use the import strategy flag, the execution time is multiple times shorter (exact time) and I don't get this warning. Is this the expected behavior or am I not executing the strategy import properly?

Furthermore, is there a way to verify that the NN was actually split according to the strategy file, e.g. by printing the resulting split graph to a text file?

**Comment by jiazhihao** [comment] 2021-06-08 07:24
I can reproduce this on my side. The issue is a mismatch between the parallelization strategy used by the dataloader and the first layer. I am working on a fix for this.

**Closed** 2022-11-03 06:32 UTC
