### ISSUE TITLE
Spec infer C++ examples blocked

### ISSUE THREAD

**Issue by reyna-abhyankar** [flexflow/FlexFlow#1319] opened 2024-03-07 02:18 UTC
Specifically, https://github.com/flexflow/FlexFlow/blob/0d75c1042bf87e45684bcb3679cfc9f39a87e589/src/runtime/request_manager.cc#L314

This may be a background server issue, since the `serve_xxxx()` functions aren't called.

This is for running `spec_infer.cc` and `incr_decoding.cc` examples.

**Comment by jiazhihao** [comment] 2024-03-08 15:15
What's the command line you used?

**Comment by goliaro** [comment] 2024-03-10 20:22
@reyna-abhyankar, you need to add the flag `-ll:cpu 4`. We should update the docs. Let me know if you are still encountering the issue with the CPU flag.

**Comment by goliaro** [comment] 2024-03-12 03:42
Feel free to reopen if the issue is not fixed, closing for now after our discussion on Slack

**Closed by goliaro** 2024-03-12 03:42 UTC
Labels: bug, inference
